hsd_on_sec:
    resource: "@HSDOnSecBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    path:     /dashboard
    defaults: { _controller: "HSDOnSecBundle:Dashboard:index" }
    methods:  GET

ajax_search:
    path:     /dashboard/search
    defaults: { _controller: "HSDOnSecBundle:Dashboard:search" }
    methods:  GET

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ajax_semester_filter:
    path:     /dashboard/semester_filter
    defaults: { _controller: "HSDOnSecBundle:Dashboard:semesterFilter" }
    options:
        expose: true