instruction_index:
    path:     /
    defaults: { _controller: "HSDOnSecBundle:Instruction:index" }
    methods:  GET

instruction_show:
    path:     /{id}/show
    defaults: { _controller: "HSDOnSecBundle:Instruction:show" }
    methods:  GET

instruction_new:
    path:     /new
    defaults: { _controller: "HSDOnSecBundle:Instruction:new" }
    methods:  [GET, POST]

room_autocomplete:
    path:     /new/autocomplete_r
    defaults: {_controller: "HSDOnSecBundle:Instruction:autocomplete_room" }
    methods:  GET

instruction_edit:
    path:     /{id}/edit
    defaults: { _controller: "HSDOnSecBundle:Instruction:edit" }
    methods:  [GET, POST]

instruction_delete:
    path:     /{id}/delete
    defaults: { _controller: "HSDOnSecBundle:Instruction:delete" }
    methods:  DELETE

instruction_run:
    path:     /{id}/run
    defaults: { _controller: "HSDOnSecBundle:Instruction:run" }
    methods:  GET

instruction_runQuestions:
    path:     /{id}/runQuestions
    defaults: { _controller: "HSDOnSecBundle:Instruction:runQuestions" }
    methods:  GET