subscriber_index:
    path:     /
    defaults: { _controller: "HSDOnSecBundle:Subscriber:index" }
    methods:  GET

subscriber_show:
    path:     /{id}/show
    defaults: { _controller: "HSDOnSecBundle:Subscriber:show" }
    methods:  GET

subscriber_new:
    path:     /new
    defaults: { _controller: "HSDOnSecBundle:Subscriber:new" }
    methods:  [GET, POST]

subscriber_edit:
    path:     /{id}/edit
    defaults: { _controller: "HSDOnSecBundle:Subscriber:edit" }
    methods:  [GET, POST]

subscriber_delete:
    path:     /{id}/delete
    defaults: { _controller: "HSDOnSecBundle:Subscriber:delete" }
    methods:  DELETE
