OnSec\OnSecBundle\Entity\Instruction:
    type: entity
    repositoryClass: OnSec\OnSecBundle\Repository\InstructionRepository
    table: instruction

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            nullable: false
        expiretime:
            type: integer
            nullable: false
        pdfLink:
            type: string
            nullable: false

    manyToOne:
        owner:
            targetEntity: User
            joinColumn:
                name: owner_id
                referencedColumnName: id

    oneToMany:
        completed_instructions:
            targetEntity: CompletedInstruction
            mappedBy: instruction


    manyToMany:
        moderators:
            targetEntity: User
            joinTable:
                name: instruction_moderators
                joinColumns:
                    instruction_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    moderator_id:
                        referencedColumnName: id
        questions:
            targetEntity: Question
            cascade: ["persist", "merge"]
            joinTable:
                name: instruction_questions
                joinColumns:
                    instruction_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    question_id:
                        referencedColumnName: id
        keywords:
            targetEntity: Keyword
            cascade: ["persist", "merge"]
            joinTable:
                name: instruction_keywords
                joinColumns:
                    instruction_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    keyword_id:
                        referencedColumnName: id

        rooms:
            targetEntity: Room
            cascade: ["persist", "merge"]
            inversedBy: instructions
            joinTable:
                name: room_instructions
                joinColumns:
                    instruction_id:
                        referencedColumnName: id
                inversedJoinColumn:
                    room_id:
                        referencedColumnName: id
