OnSec\OnSecBundle\Entity\Instruction:
    type: entity
    table: instruction

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            nullable: false
        expiredate:
            type: datetime
            nullable: false
        pdfLink:
            type: string
            nullable: false

    oneToOne:
        owner:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id

    oneToMany:
        #questions:
            #targetEntity: Question
            #mappedBy: instruction
        keywords:
            targetEntity: Keyword
            mappedBy: instruction
        moderators:
            targetEntity: User
            mappedBy: instruction

    manyToOne:
        course:
            targetEntity: Course
            inversedBy: instructions
            joinColumn:
                name: instruction_id
                referencedColumnName: id

    manyToMany:
        questions:
            targetEntity: Question
            joinTable:
                name: instructions_questions
                joinColumns:
                    instruction_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    question_id:
                        referencedColumnName: id
                        unique: true