OnSec\OnSecBundle\Entity\Keyword:
    type: entity
    repositoryClass: OnSec\OnSecBundle\Repository\KeywordRepository
    table: keyword

    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            nullable: false
