OnSec\OnSecBundle\Entity\Question:
    type: entity
    table: question

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        questionText:
            type: text
            nullable: true
        imagePath:
            type: string
            nullable: true
        createdOn:
            type: datetime
            nullable: true
        updatedOn:
            type: datetime
            nullable: true

    manyToOne:
        owner:
            targetEntity: User
            joinColumn:
                name: owner_id
                referencedColumnName: id

    oneToMany:
        answers:
            cascade: ["persist", "merge"]
            targetEntity: Answer
            mappedBy: question
