OnSec\OnSecBundle\Entity\Role:
    type: entity
    table: role

    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false

    manyToOne:
        user:
            targetEntity: User
            inversedBy: roles
            joinColumn:
                name: user_id
                referencedColumnName: id