OnSec\OnSecBundle\Entity\Rolle:
    type: entity
    table: rolle
    uniqueConstraints:
        rolle_id_UNIQUE:
            columns:
                - rolle_id
        bezeichnung_UNIQUE:
            columns:
                - bezeichnung
    id:
        rolleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: rolle_id
            generator:
                strategy: IDENTITY
    fields:
        bezeichnung:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
