OnSec\OnSecBundle\Entity\Room:
    type: entity
    table: room

    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            nullable: false

    manyToMany:
        keywords:
            targetEntity: Keyword
            joinTable:
                name: room_keywords
                joinColumns:
                    room_id:
                        referencedColumnName: id
                inverseJoinColumn:
                    keyword_id:
                        referencedColumnName: id