OnSec\OnSecBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        surname:
            type: string
            nullable: false
        firstname:
            type: string
            nullable: false
        email:
            type: string
            nullable: false
        notificationActive:
            type: boolean
            nullable: true

    manyToOne:
        instruction:
            targetEntity: Instruction
            inversedBy: moderators
            joinColumn:
                name: instruction_id
                referencedColumnName: id

    oneToMany:
        roles:
            targetEntity: Role
            mappedBy: user

    manyToMany:
        subscriber:
            targetEntity: Course
            mappedBy: subscribers
        moderators:
            targetEntity: Course
            mappedBy: moderators
