OnSec\OnSecBundle\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        surname:
            type: string
            nullable: false
        firstname:
            type: string
            nullable: false
        email:
            type: string
            nullable: false
        notificationActive:
            type: boolean
            nullable: true

    oneToMany:
        roles:
            targetEntity: Role
            mappedBy: user
