hsd_on_sec_homepage:
    path:     /
    defaults: { _controller: HSDOnSecBundle:Default:index }

hsd_on_sec_answer:
    resource: "@HSDOnSecBundle/Resources/config/routing/answer.yml"
    prefix:   /answer

hsd_on_sec_course:
    resource: "@HSDOnSecBundle/Resources/config/routing/course.yml"
    prefix:   /course

hsd_on_sec_instruction:
    resource: "@HSDOnSecBundle/Resources/config/routing/instruction.yml"
    prefix:   /instruction

hsd_on_sec_keyword:
    resource: "@HSDOnSecBundle/Resources/config/routing/keyword.yml"
    prefix:   /keyword

hsd_on_sec_question:
    resource: "@HSDOnSecBundle/Resources/config/routing/question.yml"
    prefix:   /question

hsd_on_sec_role:
    resource: "@HSDOnSecBundle/Resources/config/routing/role.yml"
    prefix:   /role

hsd_on_sec_room:
    resource: "@HSDOnSecBundle/Resources/config/routing/room.yml"
    prefix:   /room

hsd_on_sec_user:
    resource: "@HSDOnSecBundle/Resources/config/routing/user.yml"
    prefix:   /user

hsd_on_sec_completedinstruction:
    resource: "@HSDOnSecBundle/Resources/config/routing/completedinstruction.yml"
    prefix:   /completedinstruction

hsd_on_sec_subscriber:
    resource: "@HSDOnSecBundle/Resources/config/routing/subscriber.yml"
    prefix:   /subscriber

register:
    path:     /register
    defaults: { _controller: HSDOnSecBundle:Registration:register}

index:
    path:     /index
    defaults: { _controller: HSDOnSecBundle:Dashboard:index }

login:
    path:     /login
    defaults: { _controller: HSDOnSecBundle:Default:index }

createCSV:
    path:     /createCSV/{course_id}/{semester_key}
    defaults: { _controller: HSDOnSecBundle:Dashboard:createCSV }
    requirements:
      semester_key: .+

addSubscriber:
    path:     /addSubscriber/{course_id}
    defaults: { _controller: HSDOnSecBundle:Dashboard:addSubscriber }

logout:
    path:     /logout
