<?php

namespace OnSec\OnSecBundle\Repository;

/**
 * CompletedInstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompletedInstructionRepository extends \Doctrine\ORM\EntityRepository
{
}
