<?php

namespace OnSec\OnSecBundle\Repository;

/**
 * InstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructionRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($term){



        return $this->createQueryBuilder('instruction')
                        ->join('instruction.keywords','k','WITH','k.description LIKE :searchTerm')
                        ->setParameter('searchTerm', '%'.$term.'%')
                        ->getQuery()
                        ->execute();
    }
}

//->orWhere('instruction.description LIKE :searchTerm')
