<?php

namespace OnSec\OnSecBundle\Repository;

/**
 * InstructionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructionRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($term){


        $result1 = $this->createQueryBuilder('instruction', 'instruction.id')
                                ->where('instruction.description LIKE :searchTerm')
                                ->setParameter('searchTerm', '%'.$term.'%')
                                ->getQuery()
                                ->getResult();
                                //->execute();
        $result2 = $this->createQueryBuilder('instruction', 'instruction.id')
                                ->join('instruction.keywords','k','WITH','k.description LIKE :searchTerm')
                                ->setParameter('searchTerm', '%'.$term.'%')
                                ->getQuery()
                                ->getResult();

        /*$result3 = $this->createQueryBuilder('instruction','instruction.id')
                                ->join('instruction.keywords')

                    return $this->createQueryBuilder('room')
                        ->andWhere('room.description LIKE :searchTerm')
                        ->setParameter('searchTerm', '%'.$term.'%')
                        ->getQuery()
                        ->execute();*/

        return $result1+$result2;
    }
}

