<?php

namespace OnSec\OnSecBundle\Repository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends \Doctrine\ORM\EntityRepository
{
  public function search($term) {
      return $this->createQueryBuilder('keyword')
        ->andWhere('keyword.description LIKE :searchTerm')
        ->setParameter('searchTerm', '%'.$term.'%')
        ->getQuery()
        ->execute();
  }
}
