<?php

namespace OnSec\OnSecBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($term){

        return $this->createQueryBuilder('user')
            ->andWhere('user.surname LIKE :searchTerm OR user.email LIKE :searchTerm OR user.firstname LIKE :searchTerm')
            ->setParameter('searchTerm', '%'.$term.'%')
            ->getQuery()
            ->execute();
    }
}
