OnSec\OnSecBundle\Entity\Frage:
    type: entity
    table: frage
    indexes:
        user_id_idx:
            columns:
                - user_id
        unterweisung_id_idx:
            columns:
                - unterweisung_id
    uniqueConstraints:
        frage_id_UNIQUE:
            columns:
                - frage_id
    id:
        frageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: frage_id
            generator:
                strategy: IDENTITY
    fields:
        frageText:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: frage_text
        bildLink:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: bild_link
    manyToOne:
        unterweisung:
            targetEntity: Unterweisung
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unterweisung_id:
                    referencedColumnName: unterweisung_id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
